import "./ProductList.css";

import { Col, Row } from "antd";
import React, { useEffect } from "react";

import ProductCard from "../../Components/ProductCard/ProductCard";

const ProductList = () => {
  const productItems = [
    {
      name: "rebook",
      image: "product (12).jpg",
      sizes: "41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "435",
    },
    {
      name: "rebook",
      image: "product (13).jpg",
      sizes: "41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "435",
    },
    {
      name: "rebook",
      image: "product (14).jpg",
      sizes: "41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "435",
    },
    {
      name: "rebook",
      image: "product (15).jpg",
      sizes: "41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "435",
    },
    {
      name: "rebook",
      image: "product (16).jpg",
      sizes: "41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "435",
    },
    {
      name: "rebook",
      image: "product (17).jpg",
      sizes: "41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "435",
    },
    {
      name: "sneakers",
      image: "product (1).jpg",
      sizes: "39 - 40 - 41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "p123",
    },
    {
      name: "rebook",
      image: "product (2).jpg",
      sizes: "41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "320",
    },
    {
      name: "sneakers",
      image: "product (3).jpg",
      sizes: "39 - 40 - 41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "459",
    },
    {
      name: "rebook",
      image: "product (4).jpg",
      sizes: "41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "1274",
    },
    {
      name: "sneakers",
      image: "product (5).jpg",
      sizes: "39 - 40 - 41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "141",
    },
    {
      name: "rebook",
      image: "product (6).jpg",
      sizes: "41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "963",
    },
    {
      name: "rebook",
      image: "product (7).jpg",
      sizes: "41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "435",
    },
    {
      name: "rebook",
      image: "product (8).jpg",
      sizes: "41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "435",
    },
    {
      name: "rebook",
      image: "product (9).jpg",
      sizes: "41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "435",
    },
    {
      name: "rebook",
      image: "product (10).jpg",
      sizes: "41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "435",
    },
    {
      name: "rebook",
      image: "product (11).jpg",
      sizes: "41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "435",
    },

    {
      name: "rebook",
      image: "product (18).jpg",
      sizes: "41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "435",
    },
    {
      name: "rebook",
      image: "product (19).jpg",
      sizes: "41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "435",
    },
    {
      name: "rebook",
      image: "product (20).jpg",
      sizes: "41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "435",
    },
    {
      name: "rebook",
      image: "product (21).jpg",
      sizes: "41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "435",
    },
    {
      name: "rebook",
      image: "product (22).jpg",
      sizes: "41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "435",
    },
    {
      name: "rebook",
      image: "product (23).jpg",
      sizes: "41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "435",
    },
    {
      name: "rebook",
      image: "product (24).jpg",
      sizes: "41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "435",
    },
    {
      name: "rebook",
      image: "product (25).jpg",
      sizes: "41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "435",
    },
    {
      name: "rebook",
      image: "product (26).jpg",
      sizes: "41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "435",
    },
    {
      name: "rebook",
      image: "product (27).jpg",
      sizes: "41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "435",
    },
    {
      name: "rebook",
      image: "product (28).jpg",
      sizes: "41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "435",
    },
    {
      name: "rebook",
      image: "product (29).jpg",
      sizes: "41 -42 - 43 -44",
      material: "چرم",
      roof: "پلاستیکی",
      color: "مشکی - سفید - آبی - طوسی",
      price: "128/000",
      code: "435",
    },
  ];
  useEffect(() => {
    alert(
      "میتوانید قبل از انتخاب و بازدید از محصولات ، برای آشنایی با نحوه انتخاب یک کفش مناسب به صفحه مقالات مراجعه کنید"
    );
  },[window.onchange]);
  return (
    <>
      <div className="productlist-container">
        <Row align="middle" justify="space-around">
          {productItems.map((productItem) => (
            <ProductCard productItem={productItem} />
          ))}
        </Row>
      </div>
    </>
  );
};

export default ProductList;
